version: 2
updates:
  - package-ecosystem: "pip"
    directory: "docs/docsite/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "docs"
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "requirements/"
    schedule:
      interval: "daily" #run daily until we trust it, then back this off to weekly
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
